refactor(workflows): testing reusable clang tidy 3

diff --git a/.github/workflows/reusable-clang-tidy.yaml b/.github/workflows/reusable-clang-tidy.yaml
--- a/.github/workflows/reusable-clang-tidy.yaml
+++ b/.github/workflows/reusable-clang-tidy.yaml
@@ -84,21 +84,30 @@ jobs:
           path: ${{ steps.ros_ci.outputs.ros-workspace-directory-name }}/build/compile_commands.json
 
   # Second Job: Download and Run Clang-Tidy
-  clang_tidy:
+  clang_tidy_review:
     runs-on: ubuntu-latest
-    needs: build  # This ensures that clang_tidy runs after the build job completes
+    needs: build
     steps:
-      - name: Download compile_commands.json
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Download compile_commands.json artifact
         uses: actions/download-artifact@v3
         with:
           name: compile_commands
-          path: ./build  # Store in ./build where clang-tidy expects it
+          path: ./build
 
-      - name: Install Clang-Tidy
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y clang-tidy-${{ inputs.clang_tidy_version }}
+      - name: Run Clang Tidy Review
+        uses: ZedThree/clang-tidy-review@v0.20.0
+        id: review
+        with:
+          token: ${{ github.token }}
+          build_dir: './build'  # Location of compile_commands.json
+          clang_tidy_version: '18'
+          clang_tidy_checks: '-*,performance-*,readability-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*'
+          include: "*.[ch],*.[ch]xx,*.[ch]pp,*.[ch]++,*.cc,*.hh"
+          max_comments: 25
 
-      - name: Run Clang-Tidy
-        run: |
-          find src -name '*.cpp' -o -name '*.hpp' | xargs clang-tidy-${{ inputs.clang_tidy_version }} -p build
+      # Optional: Fail if clang-tidy comments were generated
+      - if: steps.review.outputs.total_comments > 0
+        run: exit 1
